[package]
name = "i3-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
pretty-hex = "0.3.0"
serde_json = "1.0.107"
